---
title: "Using astroBayes"
author: "Robin B. Trayler"
output: rmarkdown::html_vignette
bibliography: /Users/robintrayler/Zotero/ref_library.bib
csl: /Users/robintrayler/Zotero/styles/geology.csl
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction
This package contains a *very* basic method to integrate radioisotopic geochronology and cyclostratigraphy in a Bayesian framework. These methods are currently under development and is not publication ready.

The package can be loaded using the `library()` function. 

```{r setup}
library(astroBayes)
```


```{r}
# load the example data sets --------------------------------------------------
geochron_data    <- read.csv(file = '../data/data_A/radioisotopic_dates.csv')
cyclostrat_data  <- read.csv(file = '../data/data_A/cyclostratigraphic_record.csv')
tuning_frequency <- read.csv(file = '../data/data_A/tuning_frequency.csv')
true_data        <- read.csv(file = '../data/data_A/true_age.csv')
segment_edges    <- read.csv(file = '../data/data_A/segment_edges.csv')
new_positions    <- read.csv(file = '../data/data_A/new_positions.csv')
```

```{r}
# run the age model -----------------------------------------------------------
model_output <- astro_bayes_model(geochron_data = geochron_data,
                                  cyclostrat_data = cyclostrat_data,
                                  tuning_frequency = tuning_frequency,
                                  segment_edges = segment_edges,
                                  sed_prior_range = c(0, 20),
                                  iterations = 10000,
                                  burn = 1000)

# plot the results ------------------------------------------------------------
plot(model_output, type = 'age_depth')
plot(model_output, type = 'sed_rate')
plot(model_output, type = 'trace')
plot(model_output, type = 'periodogram')

# predict age for new positions -----------------------------------------------
new_positions <- predict(model_output,
                         new_positions)

plot(new_positions)
```

# References
:::{#refs}
:::
